### PR TITLE
Fixed ammo crates for ammo with 'icons'

### PR DESCRIPTION
**Pull request by More-Wrong**
This is a fix for issue  #387 of Reika_FactorioMods_Issues

 Crash on ammo item using 'icons' instead of 'icon' #387

### CODE REVIEW

**Comment by More-Wrong** [comment]
I added another change to fix a localisation issue when the item has a localised_name specified.

**Comment by FlareFlo** [comment]
Merge possible? This currently makes a few nice mods unusable :(

**Comment by More-Wrong** [comment]
The primary original issue has been resolved, although the localised name issue hasn't been fixed... Update 111 included the main patch.

**Comment by More-Wrong** [comment]
The issue for localised name is now here: https://github.com/ReikaKalseki/EndgameCombat/pull/13

**Pull request closed without merging**
